const ResumeData = [
    {
        id:1,
        category:"Schooling",
        year:"2002-2016",
        image:"",
        title:"Primary Educcation",
        desc:"From Saint Paul's Senior Secondary School",
        grade:"89%",
    },
    {
        id:3,
        category:"Schooling",
        year:"2016-2018",
        image:"",
        title:"Secondary Educcation",
        desc:"From Saint Paul's Senior Secondary School",
        grade:"81%",
    },
    {
        id:4,
        category:"Graduation",
        year:"2018-2022",
        image:"",
        title:"Graduation",
        desc:"From Lovely Professional University of Computer Sciences",
        grade:"8.22",
    },
    {
        id:5,
        category:"Graduation",
        year:"2022-2023",
        image:"",
        title:"Post Graduation",
        desc:"From Lovely Professional University of Computer Sciences",
        grade:"nil",
    },
    // {
    //     id:5,
    //     category:"",
    //     year:"",
    //     image:"",
    //     title:"",
    //     desc:"",
    //     grade:"",
    // },
    // {
    //     id:6,
    //     category:"",
    //     year:"",
    //     image:"",
    //     title:"",
    //     desc:"",
    //     grade:"",
    // }
]
export default ResumeData