const TestData = [
    {
        id:1,
        image:"https://img.icons8.com/ios/344/java-coffee-cup-logo--v1.png",
        name:"Bill Management System",
        offcer:"Acedamic Task",
        post:"",
        date:"January - 2019",
        desc:"A java based restraunt bill calculator system using the fundamentals of programming",
    },
    {
        id:2,
        image:"https://img.icons8.com/ios/344/python--v1.png",
        name:"8 X 8 Puzzle game",
        offcer:"Acedamic Task",
        post:"",
        date:"October - 2019",
        desc:"A python ui game to make words using numpy, pandas, tkinter",
    },
    {
        id:3,
        image:"https://img.icons8.com/ios-filled/344/journey.png",
        name:"TourNest",
        offcer:"Acedamic Task",
        post:"",
        date:"November - 2020",
        desc:"A front-end project on tours and travels with HTML, CSS, JS, Bootstrap.",
    },
    {
        id:4,
        image:"https://image.shutterstock.com/shutterstock/photos/691249711/display_1500/stock-vector-route-location-icon-two-map-pin-sign-and-road-or-path-start-and-end-journey-symbol-black-color-691249711.jpg",
        name:"Travelville",
        offcer:"Capsone Project",
        post:"",
        date:"August - 2021",
        desc:"A full stack project using google auth on travel management system.",
    },
    {
        id:5,
        image:"https://img.icons8.com/external-justicon-lineal-justicon/2x/external-online-shopping-ecommerce-justicon-lineal-justicon.png",
        name:"E-Commerce website",
        offcer:"Personal Intrest",
        post:"",
        date:"January - 2022",
        desc:"A Flipkart clone app with google auth and Mongo DB, Express, React & Node.",
    },
    {
        id:6,
        image:"https://img.icons8.com/fluency-systems-regular/344/portfolio.png",
        name:"Personal Portfolio",
        offcer:"Professional resume",
        post:"",
        date:"January - 2022",
        desc:"A personal portfolio website built using React & deployed on github using gh-pages.",
    },
]
export default TestData;